title: Mauricio Freitas
author: Mauricio Freitas
email: contato@mauriciofreitas.eng.br
description: >
  Simples blog para documentar e compartilhar as pequenas descobertas
  interessantes de meu dia-a-dia.
baseurl: ""
url: "https://meunomemauricio.github.io"
github_username: meunomemauricio

# Build settings
markdown: kramdown
