title: Mauricio Freitas
author: Mauricio Freitas
email: contato@mauriciofreitas.eng.br
description:
  pt: >
    Simples blog para documentar e compartilhar descobertas interessantes.
  en: >
    Simple blog to documment and share interesting discoveries.
baseurl: ""
url: "https://meunomemauricio.github.io"
github_username: meunomemauricio
languages:
  pt: Português
  en: English

# Build settings
markdown: kramdown
